In [1]:
import pandas as pd
import requests

In [5]:
# Obter dados de câmbio do BCB
url = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.10813/dados"
params = {
    "formato": "json",
    "dataInicial": "01/01/2023",
    "dataFinal": "31/12/2024"
}

response = requests.get(url, params=params)
cambio = pd.DataFrame(response.json())

pd.concat([cambio.head(5), cambio.tail(5)])

           data   valor
0    02/01/2023  5.3430
1    03/01/2023  5.3753
2    04/01/2023  5.4453
3    05/01/2023  5.4020
4    06/01/2023  5.2849
497  24/12/2024  6.1527
498  26/12/2024  6.1650
499  27/12/2024  6.1985
500  30/12/2024  6.1917
501  31/12/2024  6.1917

In [7]:
# Tratamento dos dados do BCB
cambio["data"] = pd.to_datetime(cambio["data"], dayfirst=True)
cambio["usd_brl"] = cambio["valor"].astype(float)

# Preencher datas faltantes 
cambio = cambio.set_index('data')
calendario_completo = pd.date_range("2023-01-01", "2024-12-31", freq="D")
cambio = cambio.reindex(calendario_completo)
cambio['usd_brl'] = cambio['usd_brl'].ffill().bfill() 
cambio = cambio.reset_index().rename(columns={'index': 'data'})

pd.concat([cambio.head(5), cambio.tail(5)])

          data   valor  usd_brl
0   2023-01-01     NaN   5.3430
1   2023-01-02  5.3430   5.3430
2   2023-01-03  5.3753   5.3753
3   2023-01-04  5.4453   5.4453
4   2023-01-05  5.4020   5.4020
726 2024-12-27  6.1985   6.1985
727 2024-12-28     NaN   6.1985
728 2024-12-29     NaN   6.1985
729 2024-12-30  6.1917   6.1917
730 2024-12-31  6.1917   6.1917

In [9]:
# Carregar Vendas e Custos
vendas = pd.read_csv('../datasets/vendas_2023_2024.csv')
custos = pd.read_csv('../datasets/custos_importacao.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../datasets/custos_importacao.csv'